<?php

namespace App\Main\Components;

use App\Main\Helpers\BootstrapTag;
use Phalcon\Di\FactoryDefault\Cli;

/**
 * App\Main\Components\DI
 *
 * @property \Phalcon\Logger\AdapterInterface $logger;
 * @property SecurityManager $securityManager
 * @property \Phalcon\Mvc\Model\Metadata\Memcache $modelsMetadata
 * @property TripManager $tripManager
 * @property BootstrapTag $tag
 * @property Acl $acl
 * @property \Phalcon\Cache\Backend\Memcache $cache
 * @property \Phalcon\Security $security
 * @property \Phalcon\Session\Adapter\Files|\Phalcon\Session\Adapter|\Phalcon\Session\AdapterInterface $session
 */
class CliDI extends Cli
{
	private $_skippedServices = ['dispatcher', 'router'];
	public function __get($propertyName)
	{
		return $this->get($propertyName);
	}

	public function set($name, $definition, $shared = false)
	{
		if (in_array($name, $this->_skippedServices)) {
			return;
		}
		parent::set($name, $definition, $shared); // TODO: Change the autogenerated stub
	}

}